//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AttachmentPlaceholder {
            get {
                object obj = ResourceManager.GetObject("AttachmentPlaceholder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CustomerDetailsIcon {
            get {
                object obj = ResourceManager.GetObject("CustomerDetailsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmployeeDetailsIcon {
            get {
                object obj = ResourceManager.GetObject("EmployeeDetailsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenericHeader {
            get {
                object obj = ResourceManager.GetObject("GenericHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InventoryHeader {
            get {
                object obj = ResourceManager.GetObject("InventoryHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Invoice #81&lt;/title&gt;
        ///	&lt;style&gt;
        ///		body {
        ///			font-family: &quot;Arial&quot;;
        ///			font-size: .8em;
        ///		}
        ///		dir {
        ///			width: 290px;
        ///		}
        ///		label {
        ///			width: 7em;
        ///			color: rgb(127,0,27);
        ///		}
        ///		h1 {
        ///			color: rgb(127,0,27);
        ///			font-style: normal;
        ///			font-weight: normal;
        ///			height: 65px;
        ///			margin-top: 20px;
        ///		}
        ///		th {
        ///			padding: 1px;
        ///			font-size: .75em;
        ///			display: block;
        ///			background: rgb(199,197,188);
        ///			color: white;
        ///		}
        ///		td {
        ///			background: white;
        ///			border-bottom: 1px [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InvoiceTemplate {
            get {
                return ResourceManager.GetString("InvoiceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Invoice #81&lt;/title&gt;
        ///	&lt;style&gt;
        ///		body {
        ///			font-family: &quot;Arial&quot;;
        ///			font-size: .8em;
        ///		}
        ///		dir {
        ///			width: 290px;
        ///		}
        ///		label {
        ///			width: 7em;
        ///			color: rgb(127,0,27);
        ///		}
        ///		h1 {
        ///			color: rgb(127,0,27);
        ///			font-style: normal;
        ///			font-weight: normal;
        ///			height: 65px;
        ///			margin-top: 20px;
        ///		}
        ///		th {
        ///			padding: 1px;
        ///			font-size: .75em;
        ///			display: block;
        ///			background: rgb(199,197,188);
        ///			color: white;
        ///		}
        ///		td {
        ///			background: white;
        ///			border-bottom: 1px [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InvoiceTemplateDemo {
            get {
                return ResourceManager.GetString("InvoiceTemplateDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoginDialogBackground {
            get {
                object obj = ResourceManager.GetObject("LoginDialogBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoLarge {
            get {
                object obj = ResourceManager.GetObject("LogoLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrderDetailsIcon {
            get {
                object obj = ResourceManager.GetObject("OrderDetailsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrderListIcon {
            get {
                object obj = ResourceManager.GetObject("OrderListIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PortraitPlaceholder {
            get {
                object obj = ResourceManager.GetObject("PortraitPlaceholder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProductDetailsIcon {
            get {
                object obj = ResourceManager.GetObject("ProductDetailsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PurchaseOrderDetailsIcon {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrderDetailsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PurchaseOrdersList {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrdersList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RefreshIcon {
            get {
                object obj = ResourceManager.GetObject("RefreshIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShipperDetailsIcon {
            get {
                object obj = ResourceManager.GetObject("ShipperDetailsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartupHeader {
            get {
                object obj = ResourceManager.GetObject("StartupHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SupplierDetailsIcon {
            get {
                object obj = ResourceManager.GetObject("SupplierDetailsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
